development:
  mysql41: 3976
  enable_star: true
  min_infix_len: 1
  charset_type: utf-8
  morphology: 'stem_en'
  charset_table: "0..9, a..z, _, @, A..Z->a..z, U+400..U+4FF, U+430..U+458, U+0026, U+42F, U+44F, U+043B, U+041B, U+0407, U+0406, U+0456, U+0457"
  bin_path: '/usr/bin'
  ignore_chars: U+0027, U+0022
  mem_limit: 64M
